- name: Fetch FQDNs from inventory
  hosts: all
  gather_facts: false
  vars:
    servernames_Unix:
      - appserver01

  tasks:

    - name: Print available facts for each host
      debug:
        var: hostvars[item]
      loop: "{{ servernames_Unix }}"
      
    - name: Fetch FQDNs from inventory
      set_fact:
        fqdn_list: "{{ fqdn_list | default([]) + [hostvars[item]['ansible_fqdn']] }}"
      loop: "{{ servernames_Unix }}"

    - name: Display the result
      debug:
        var: fqdn_list
