---
- name: Merge CSV files
  hosts: ansible-lab
  become: yes
  tasks:
    - name: Find CSV files
      find:
        paths: /tmp/test/tmp
        patterns: "*.csv"
        recurse: yes
      register: csv_files

#    - name: Merge CSV files
#      lineinfile:
#        dest: /tmp/test/final.csv
#        insertafter: EOF
#        line: "{{ lookup('file', item.path) }}"
#        create: true
#      delegate_to: ansible-lab
#      loop: "{{ csv_files.files }}"
      


    - name: Merge CSV files
      lineinfile:
        dest: /tmp/test/final.csv
        insertafter: EOF
        line: "{{ item }}"
        create: true
      loop: "{{ csv_files.files | map('extract', 'path') | map('file') | list }}"
