- name: Fetch FQDNs from inventory
  hosts: appserver01
  gather_facts: false
  vars:
    servernames_Unix:
      - appserver01

  tasks:
    - name: Fetch FQDNs from inventory
      set_fact:
        fqdn_list: "{{ fqdn_list | default([]) + [hostvars[item]['fqdn']] }}"
      loop: "{{ servernames_Unix }}"

    - name: Display the result
      debug:
        var: fqdn_list
