---
- name: Execute PowerShell Script
  hosts: ansible-lab  # Change this if you want to run on a different host
  tasks:
    - name: Execute PowerShell script with parameters
      shell: |
        pwsh "/home/admin1/Desktop/GraphQL/rubrik_sdk_graphql_events_specific_param.ps1" -client_secret "pYCSC3uwlqb5h25bARrfFQO4ooS3a_2n6iZFaElv0gVPT8XL7fqQSKEyIW41PkLa" -access_token_uri "https://kyndrylinc.my.rubrik.com/api/client_token"