---
- name: Execute PowerShell Script
  hosts: ansible-lab # Change this to your target host
  become: true
  gather_facts: false
  tasks:
    - name: Set Fact the Credentials and Tokens
      set_fact:
        account_name: "{{ lookup('env', 'RSC_ACCOUNT_NAME') }}"
        URI: "{{ lookup('env', 'RSC_TOKEN') }}"
        client_id: "{{ lookup('env', 'RSC_ID') }}"
        rsc_client_secret: "{{ lookup('env', 'RSC_SECRET') }}"
      no_log: true

    - name: Remove Directory
      file:
        path: /home/admin1/Desktop/GraphQL
        state: absent

    - name: Remove Directory
      file:
        path: /home/admin1/Desktop/GraphQL/queries
        state: absent

    - name: Create directory
      file:
        path: /home/admin1/Desktop/GraphQL
        state: directory

    - name: Create directory
      file:
        path: /home/admin1/Desktop/GraphQL/queries
        state: directory

    - name: Copy PowerShell script from playbook repository
      copy:
        src: 'files/rubrik_sdk_graphql_events_specific_param.ps1'
        dest: /home/admin1/Desktop/GraphQL/

    - name: Copy PowerShell script from playbook repository
      copy:
        src: 'files/Getevents.gql'
        dest: /home/admin1/Desktop/GraphQL/queries/

    - name: Execute PowerShell script with parameters
      shell: |
        pwsh rubrik_sdk_graphql_events_specific_param.ps1 -client_id "{{ client_id }}" -client_secret "{{ rsc_client_secret }}" -access_token_uri "{{ URI }}" -lastUpdatedTimeGt "{{ lastUpdatedTimeGt }}" -lastUpdatedTimeLt "{{ lastUpdatedTimeLt }}"
      args:
        chdir: /home/admin1/Desktop/GraphQL
      no_log: true
