---
- name: Merge CSV files
  hosts: ansible-lab
  become: yes
  tasks:
      - name: To fetch the credential and get the data
        set_fact:
            account_name: "{{ lookup('env', 'RSC_ACCOUNT_NAME') }}"
            URI: "{{ lookup('env', 'RSC_TOKEN') }}"
            client_id: "{{ lookup('env', 'RSC_ID') }}"
            rb_client_secret: "{{ lookup('env', 'RSC_SECRET') }}"
        no_log: true

      - name: To print
        debug:
          msg: "Accountname: {{ account_name }}  Access Token URI : {{ URI }} CLientID: {{ client_id }} ClientSecert: {{ rb_client_secret }}"


#    - name: Merge CSV files
#      lineinfile:
#        dest: /tmp/test/final.csv
#        insertafter: EOF
#        line: "{{ item }}"
#        create: true
#      loop: "{{ csv_files.files | map('extract', 'path') | map('file') | list }}"
