---
- name: Execute PowerShell Script
  hosts: ansible-lab  # Change this to your target host
  become: true
  tasks:
    - name: Execute PowerShell script with parameters
      shell: |
        pwsh rubrik_sdk_graphql_events_specific_param.ps1 -client_id "client|a5724bec-b375-4f78-88a5-20c81bf260bd" -client_secret "pYCSC3uwlqb5h25bARrfFQO4ooS3a_2n6iZFaElv0gVPT8XL7fqQSKEyIW41PkLa" -access_token_uri "https://kyndrylinc.my.rubrik.com/api/client_token"
      args:
        chdir: /home/admin1/Desktop/GraphQL
