---
- name: Execute PowerShell Script
  hosts: ansible-lab  # Change this to your target host
  become: true
  tasks:
    - name: Execute PowerShell script with parameters
      shell: |
        pwsh rubrik_sdk_graphql_events_specific_param.ps1 -client_id "{{ lookup('env', 'rb_client_id') }}" -client_secret"{{ lookup('env', 'rb_client_secret') }}" -access_token_uri "{{ lookup('env', 'rb_acces_token_uri') }}"
      args:
        chdir: /home/admin1/Desktop/GraphQL
